### PR TITLE
Update python requirements

### LINKED ISSUE #49: Drop support for older versions of python
Looks like this project is still testing against python 3.6, which I don't think is supported by the github CI runners for ubuntu anymore. This will make testing more difficult as time progresses.

While we are at it should python 3.7 support be dropped as well? The main `astropy` project has already dropped it.

### PR DESCRIPTION
**Pull request by WilliamJamieson**
This PR updates the python requirements and CI.

Fixes #49

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
I give up, on fixing the `linuxgcc` CI. @Cadair do you know how to fix this?

**Comment by astrofrog** [comment]
I can try and look into this on Monday

**Comment by astrofrog** [comment]
The conda issue appears to have resolved itself, so I am just fixing a couple of deprecations and will get this merged once the CI passes.

**Comment by astrofrog** [comment]
The SunPy test failure is unrelated, so I'll go ahead and merge

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
