### PR TITLE
Fix leaked temporary directory in check_openmp_support

### PR DESCRIPTION
**Pull request by lpsinger**
See also astropy/astropy-helpers#511.

### CODE REVIEW

**Comment by pllim** [comment]
The failures here are totally different from `astropy-helpers`. Here, failure only affects Windows and OSX and seems to be related to C compiler/linker.

**Comment by pllim** [comment]
Ah, looks like part of the failure was reported in #15

**Comment by pllim** [comment]
I think this will pass after a rebase after #21 is merged. 🤞

**Comment by astrofrog** [comment]
@lpsinger - can you rebase now that the CI was fixed in #21/#22?

**Comment by pllim** [comment]
Tests passed!

**Review by astrofrog — APPROVED** [review]
Apologies for the long delay in merging this - looks good!

**Pull request merged**
