### PR TITLE
MNT: Replace master with main

### PR DESCRIPTION
**Pull request by pllim**
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.

This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.

This is part of #27

### CODE REVIEW

**Comment by pllim** [comment]
style job failure about `isort` is unrelated.

**Comment by pllim** [comment]
Done!

**Comment by pllim** [comment]
Is it just me or Azure much slower than Actions now?

**Comment by embray** [comment]
> Is it just me or Azure much slower than Actions now?

I hadn't specifically noticed, but I feel like almost all of these CI providers are being pressured by their investors to throttle free use for open source.  It happened (badly) to Travis.  I wouldn't be surprised if it's happening with Azure.  Possibly so MS can shift more resources to GH Actions.  But it'll happen with GH too, I'm sure of it.

**Pull request merged**
